In [5]:
import numpy as np 
import pandas as pd

In [10]:
np.random.seed(101) # para os valores ficarem iguais aos da aula

In [11]:
df = pd.DataFrame(np.random.randn(5,4), index= 'A B C D E'.split(), columns = 'W X Y Z'.split())

In [12]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [13]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [14]:
type(df['W'])

pandas.core.series.Series

In [15]:
type(df)

pandas.core.frame.DataFrame

In [18]:
df[['W', 'Z']]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [19]:
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [20]:
df['new'] = df['W'] + df['X']

In [21]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [23]:
df.drop('new', axis=1)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [24]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [27]:
df.drop('new', axis=1, inplace=True)

In [28]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [29]:
df.loc['A', 'W'] # serve para fazer seleções

np.float64(2.706849839399938)

In [30]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [31]:
df.loc[['A', 'B'], ['X', 'Y', 'Z']] # por idx

          X         Y         Z
A  0.628133  0.907969  0.503826
B -0.319318 -0.848077  0.605965

In [32]:
df.iloc[1:4, 2:] #que nem no np

          Y         Z
B -0.848077  0.605965
C  0.528813 -0.589001
D -0.933237  0.955057