In [3]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
df = pd.DataFrame({'A':[1, 2, np.nan], 'B': [5, np.nan, np.nan], 'C':[1,2,3]})

In [7]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [6]:
df.dropna() # padrão é axis=0 portanto se tem nan na linha ela é excluida

     A    B  C
0  1.0  5.0  1

In [7]:
df.dropna(axis=1) # assim se tiver nan na coluna ela será excluida

   C
0  1
1  2
2  3

In [11]:
df.dropna(thresh=2) # vai excluir as linhas que possuirem a quantidae pasada de valores faltantes aqui foi 2 mas poderia ser qualquer um

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [13]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [16]:
df .fillna(method='ffill') # foward fill substitui o nan pelo anterior a ele na coluna

C:\Users\newst\AppData\Local\Temp\ipykernel_14696\519937875.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df .fillna(method='ffill') # foward fill substitui o nan pelo anterior a ele na coluna

     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  2.0  5.0  3

In [18]:
# assim apos eu rodar aparece esse aviso de que o method é não esta mais sendo muito utilizado e em versões futuras ele pode deixar de funcionar no pandas
df.ffill() 3 essa é a versão atualaizada

     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  2.0  5.0  3