In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [3]:
df['col2'].unique() # ele devolve apensa valores unicos

array([444, 555, 666])

In [4]:
np.unique(df['col2'])

array([444, 555, 666])

In [27]:
df['col2'].nunique() # retorna o tamanho do evt de resposta

KeyError: 'col2'

In [6]:
df['col2'].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [7]:
newdf = df[(df['col1']>2) & (df['col2']==444)] Permite seleções com o colchetes

In [8]:
newdf

   col1  col2 col3
3     4   444  xyz

In [28]:
def vezes2(x):
    return x*2

In [29]:
df['col1'].apply(vezes2)

KeyError: 'col1'

In [11]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [12]:
df['col1'].sum()

np.int64(10)

In [13]:
del df['col1']

In [14]:
df

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [15]:
df.columns

Index(['col2', 'col3'], dtype='object')

In [16]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [17]:
df

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [18]:
df.sort_values(by='col2')

   col2 col3
0   444  abc
3   444  xyz
1   555  def
2   666  ghi

In [19]:
df.isnull()

    col2   col3
0  False  False
1  False  False
2  False  False
3  False  False

In [20]:
df.dropna()

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [21]:
import numpy as np

In [22]:
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

   col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [23]:
df.fillna('Preencher')

        col1       col2 col3
0        1.0  Preencher  abc
1        2.0      555.0  def
2        3.0      666.0  ghi
3  Preencher      444.0  xyz

In [24]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [25]:
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [26]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN