In [1]:
import numpy as np
import pandas as pd

In [3]:
from numpy.random import randn
np.random.seed(101)

In [5]:
df = pd.DataFrame(randn(5, 4), index='A B C D E'.split(), columns='W X Y Z'.split())

In [6]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [10]:
bol = df>0

In [12]:
df[bol]

          W         X         Y         Z
A  0.302665  1.693723       NaN       NaN
B       NaN  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D       NaN       NaN       NaN  0.484752
E       NaN  1.901755  0.238127  1.996652

In [18]:
df[df['W']>0]['Y']

A   -1.706086
C    0.638787
Name: Y, dtype: float64

In [19]:
bol = df['W']>0
df2 = df[bol]
df2['Y']

A   -1.706086
C    0.638787
Name: Y, dtype: float64

In [21]:
df[(df['W']>0) | (df['Y']>1)]

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [40]:
df.reset_index(inplace=True) # redefine o idx para o padrao 0 1 2...

In [27]:
df

  index         W         X         Y         Z
0     A  0.302665  1.693723 -1.706086 -1.159119
1     B -0.134841  0.390528  0.166905  0.184502
2     C  0.807706  0.072960  0.638787  0.329646
3     D -0.497104 -0.754070 -0.943406  0.484752
4     E -0.116773  1.901755  0.238127  1.996652

In [28]:
col = 'RS RJ SP AM SC'.split()

In [29]:
col

['RS', 'RJ', 'SP', 'AM', 'SC']

In [37]:
df['Estado'] = col

In [31]:
df

  index         W         X         Y         Z Estado
0     A  0.302665  1.693723 -1.706086 -1.159119     RS
1     B -0.134841  0.390528  0.166905  0.184502     RJ
2     C  0.807706  0.072960  0.638787  0.329646     SP
3     D -0.497104 -0.754070 -0.943406  0.484752     AM
4     E -0.116773  1.901755  0.238127  1.996652     SC

In [41]:
df.set_index('Estado', inplace=True) # permite atribuir uma seriees no index do DF

In [42]:
df

       index         W         X         Y         Z
Estado
RS         A  0.302665  1.693723 -1.706086 -1.159119
RJ         B -0.134841  0.390528  0.166905  0.184502
SP         C  0.807706  0.072960  0.638787  0.329646
AM         D -0.497104 -0.754070 -0.943406  0.484752
SC         E -0.116773  1.901755  0.238127  1.996652