In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']

In [4]:
inside = [1, 2, 3, 1, 2, 3]

In [6]:
hier_index = list(zip(outside,inside))

In [7]:
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [8]:
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [9]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [16]:
df  = pd.DataFrame(np.random.randn(6, 2), index=hier_index, columns=['A', 'B'])

In [17]:
df

             A         B
G1 1 -1.278931 -0.362068
   2 -1.621847  1.318895
   3 -0.107222 -0.082291
G2 1  0.455042  0.771086
   2  0.146580  1.066209
   3  0.895303 -1.792451

In [24]:
df.index.names = ['Grupo', 'Numero']

In [25]:
df

                     A         B
Grupo Numero
G1    1      -1.278931 -0.362068
      2      -1.621847  1.318895
      3      -0.107222 -0.082291
G2    1       0.455042  0.771086
      2       0.146580  1.066209
      3       0.895303 -1.792451

In [26]:
df.xs(1, level='Numero')

              A         B
Grupo
G1    -1.278931 -0.362068
G2     0.455042  0.771086